# Generated by Django 4.1.2 on 2022-10-20 11:18

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ActorsDetails',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('contact_info', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Directors',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('contact_details', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Generes',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('genere', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Movies',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50)),
                ('storyline', models.TextField()),
                ('country_of_origin', models.CharField(max_length=50)),
                ('language', models.CharField(max_length=50)),
                ('production_house', models.CharField(max_length=50)),
                ('cast', models.ManyToManyField(to='app.actorsdetails')),
                ('movie_director', models.ManyToManyField(to='app.directors')),
                ('movie_genere', models.ManyToManyField(to='app.generes')),
            ],
        ),
        migrations.CreateModel(
            name='StreamingPlatform',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('about', models.TextField()),
                ('website', models.URLField()),
            ],
        ),
        migrations.CreateModel(
            name='TechnicalSpecs',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('runtime', models.FloatField()),
                ('colour', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='Writers',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('contact_details', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Reviews',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rating', models.PositiveIntegerField()),
                ('description', models.TextField()),
                ('movies', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.movies')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddField(
            model_name='movies',
            name='movie_specs',
            field=models.ManyToManyField(to='app.technicalspecs'),
        ),
        migrations.AddField(
            model_name='movies',
            name='movie_writer',
            field=models.ManyToManyField(to='app.writers'),
        ),
        migrations.AddField(
            model_name='movies',
            name='platform',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.streamingplatform'),
        ),
    ]
